### ISSUE TITLE
hitting shift+enter should run the query

### ISSUE THREAD

**Issue by timchan-lumoslabs** [lumoslabs/aleph#16]
Many notebook tools like Databricks, Zeppelin and Jupyter utilize the keyboard shortcut of shift+enter to execute the contents of a cell. It would be nice if Aleph would also support this shortcut.

**Comment by dollschasingmen** [comment]
is this running the query from within the query REPL? or is this pain you feel in other places

**Comment by timchan-lumoslabs** [comment]
Yes. I only have this issue while in the query REPL.

**Comment by dollschasingmen** [comment]
makes sense
