### ISSUE TITLE
Other connectors?

### ISSUE THREAD

**Issue by existeundelta** [lumoslabs/aleph#23]
Would be great have other connectors, how about execute python snnipets to pinkle (pandas) files?

**Comment by dollschasingmen** [comment]
There are no other connectors at this moment, although the idea is on the roadmap. Which other connectors would you want?

Not sure what you mean by executing python, do you mean Redshift UDFs? Aleph just executes code against Redshift so, as long as your permissions are set up correctly and the Aleph user can write UDFs, it *should* be possible. I have not tried this, however.

**Comment by existeundelta** [comment]
I mean other sources not just Redshift, also ElasticSearch, SqlServer, MySql, etc..
Thanks

**Comment by dollschasingmen** [comment]
Yea, no other sources at the moment, Redshift only.

**Comment by rfroetscher** [comment]
Feel free to make a PR! We'd be happy to merge a change that makes this more configurable for different connections. Happy to discuss what this might look like.

**Comment by dollschasingmen** [comment]
@existeundelta closing this for now. if you have more questions, hit us up at: https://groups.google.com/forum/#!forum/aleph-user
