### ISSUE TITLE
multiple queries return no results

### ISSUE THREAD

**Issue by frankhsu** [lumoslabs/aleph#34]
a query like this yields 0 results

```
drop table if exists scratch.frank_test;
select 2;
create table if not exists scratch.frank_test (stagename varchar, stagenum int, PRIMARY key (stagenum));
select 3;
insert into scratch.frank_test(stagename,stagenum) values ('SAL','19'),('Engaged','29'),('Qualified','39');
select 4;
select * from scratch.frank_test;
select 5;
```

it'll work only if the first query returns a result. i.e. adding `select 1;` to the top.

**Comment by dollschasingmen** [comment]
huh -- this is a pretty outside use case, it seems like you are doing more than simply querying the data (which aleph is primarily design for). 

if you need intermediate data tables, we generally use [`WITH` clause] (http://docs.aws.amazon.com/redshift/latest/dg/r_WITH_clause.html)

also this might a result of the fact that we stream data:

https://github.com/lumoslabs/aleph/blob/master/Gemfile#L29
https://github.com/lumoslabs/pg_stream/blob/master/lib/pg_stream/stream.rb#L6

The idea is that we wanted to be able to fetch arbitrarily large data sets w/o it being a memory burden on the aleph server. It also starts gets your data a lot faster in some cases.

**Comment by frankhsu** [comment]
ah got it. ill close for now. thanks!
