### ISSUE TITLE
Saved, site-wide filters for Schema search

### ISSUE THREAD

**Issue by slpsys** [lumoslabs/aleph#38]
## Motivation

For us, this comes up in two places:
- We use Octopus with Rails, and so we have a number of different physical databases with the same schema, despite the fact that only one of the databases ever contains actual data, which is confusing unless you know where to look
- We have some tables that are implementation details, and basically should never be exposed to Aleph users. They're not secret, they just aren't useful to end users

## Some thoughts on implementation

- Should only be available to admins on a per-install basis
- *Should* be available on a per-install basis
- Several filters would be desirable 
- Regular expressions would be great

**Comment by dollschasingmen** [comment]
hmm, what do you think about something like this:

    blacklist:
      - alooma.*
      - lumosity.game_r*

etc?

**Comment by slpsys** [comment]
The only thing about that is that `lumosity.game_r*` is helpful, but what about `gameresults` + ...`!(game_r*)` ?

**Comment by slpsys** [comment]
*our* case would be solved by e.g.

```
blacklist:
  - alooma.*
  - lumosity.gym_*
  - gameresults.gym_*
whitelist:
  - gym.gym_*
```
etc

**Comment by dollschasingmen** [comment]
i think this can be achieved by a blacklist that can handle regexes. w/ regexes, you can use inverses to sort of do the equivalent of whitelisting.

**Comment by slpsys** [comment]
yep, we discussed that in slack last week.

**Comment by dollschasingmen** [comment]
yes, yes we did
